use super::key::Key;
use super::event::{KeyboardEvent, KeyboardEventType};

use alloc::Vec;

pub struct Keymap {
    mapping: Option<Vec<(Vec<u8>, (Key, KeyboardEventType))>>
}

impl Keymap {
    pub const fn new() -> Keymap {
        Keymap {
            mapping: None
        }
    }

    pub fn init(&mut self) {
        use self::KeyboardEventType::*;

        self.mapping = Some(vec![
            (vec![0x05], (Key::F1, Press)),
            (vec![0x06], (Key::F2, Press)),
            (vec![0x04], (Key::F3, Press)),
            (vec![0x0C], (Key::F4, Press)),
            (vec![0x03], (Key::F5, Press)),
            (vec![0x0B], (Key::F6, Press)),
            (vec![0x0A], (Key::F8, Press)),
            (vec![0x01], (Key::F9, Press)),
            (vec![0x09], (Key::F10, Press)),
            (vec![0x78], (Key::F11, Press)),
            (vec![0x07], (Key::F12, Press)),
            (vec![0x0D], (Key::Tab, Press)),
            (vec![0x0E], (Key::Backtick, Press)),
            (vec![0x11], (Key::LeftAlt, Press)),
            (vec![0x12], (Key::LeftShift, Press)),
            (vec![0x14], (Key::LeftControl, Press)),
            (vec![0x45], (Key::K0, Press)),
            (vec![0x16], (Key::K1, Press)),
            (vec![0x1E], (Key::K2, Press)),
            (vec![0x26], (Key::K3, Press)),
            (vec![0x25], (Key::K4, Press)),
            (vec![0x2E], (Key::K5, Press)),
            (vec![0x36], (Key::K6, Press)),
            (vec![0x3D], (Key::K7, Press)),
            (vec![0x3E], (Key::K8, Press)),
            (vec![0x46], (Key::K9, Press)),
            (vec![0x1C], (Key::A, Press)),
            (vec![0x32], (Key::B, Press)),
            (vec![0x21], (Key::C, Press)),
            (vec![0x23], (Key::D, Press)),
            (vec![0x24], (Key::E, Press)),
            (vec![0x2B], (Key::F, Press)),
            (vec![0x34], (Key::G, Press)),
            (vec![0x33], (Key::H, Press)),
            (vec![0x43], (Key::I, Press)),
            (vec![0x3B], (Key::J, Press)),
            (vec![0x42], (Key::K, Press)),
            (vec![0x4B], (Key::L, Press)),
            (vec![0x3A], (Key::M, Press)),
            (vec![0x31], (Key::N, Press)),
            (vec![0x44], (Key::O, Press)),
            (vec![0x4D], (Key::P, Press)),
            (vec![0x15], (Key::Q, Press)),
            (vec![0x2D], (Key::R, Press)),
            (vec![0x1B], (Key::S, Press)),
            (vec![0x2C], (Key::T, Press)),
            (vec![0x3C], (Key::U, Press)),
            (vec![0x2A], (Key::V, Press)),
            (vec![0x1D], (Key::W, Press)),
            (vec![0x22], (Key::X, Press)),
            (vec![0x35], (Key::Y, Press)),
            (vec![0x1A], (Key::Z, Press)),
            (vec![0x29], (Key::Space, Press)),
            (vec![0x41], (Key::Comma, Press)),
            (vec![0x49], (Key::Period, Press)),
            (vec![0x4A], (Key::Slash, Press)),
            (vec![0x4C], (Key::Semicolon, Press)),
            (vec![0x4E], (Key::Minus, Press)),
            (vec![0x52], (Key::Singlequote, Press)),
            (vec![0x54], (Key::LeftBracket, Press)),
            (vec![0x55], (Key::Equals, Press)),
            (vec![0x58], (Key::CapsLock, Press)),
            (vec![0x59], (Key::RightShift, Press)),
            (vec![0x5A], (Key::Enter, Press)),
            (vec![0x5B], (Key::RightBracket, Press)),
            (vec![0x5D], (Key::Backslash, Press)),
            (vec![0x66], (Key::Backspace, Press)),
            (vec![0x69], (Key::Keypad_1, Press)),
            (vec![0x6B], (Key::Keypad_4, Press)),
            (vec![0x6C], (Key::Keypad_7, Press)),
            (vec![0x70], (Key::Keypad_0, Press)),
            (vec![0x71], (Key::Keypad_Period, Press)),
            (vec![0x72], (Key::Keypad_2, Press)),
            (vec![0x73], (Key::Keypad_5, Press)),
            (vec![0x74], (Key::Keypad_6, Press)),
            (vec![0x75], (Key::Keypad_8, Press)),
            (vec![0x76], (Key::Escape, Press)),
            (vec![0x77], (Key::NumberLock, Press)),
            (vec![0x79], (Key::Keypad_Plus, Press)),
            (vec![0x7A], (Key::Keypad_3, Press)),
            (vec![0x7B], (Key::Keypad_Minus, Press)),
            (vec![0x7C], (Key::Keypad_Multiply, Press)),
            (vec![0x7D], (Key::Keypad_9, Press)),
            (vec![0x7E], (Key::ScrollLock, Press)),
            (vec![0x83], (Key::F7, Press)),
            (vec![0xE0, 0x10], (Key::Multimedia_WWW_Search, Press)),
            (vec![0xE0, 0x11], (Key::RightAlt, Press)),
            (vec![0xE0, 0x14], (Key::RightControl, Press)),
            (vec![0xE0, 0x15], (Key::Multimedia_PreviousTrack, Press)),
            (vec![0xE0, 0x18], (Key::Multimedia_WWW_Favourites, Press)),
            (vec![0xE0, 0x1F], (Key::GUI_Left, Press)),
            (vec![0xE0, 0x20], (Key::Multimedia_WWW_Refresh, Press)),
            (vec![0xE0, 0x21], (Key::Multimedia_VolumeDown, Press)),
            (vec![0xE0, 0x23], (Key::Multimedia_Mute, Press)),
            (vec![0xE0, 0x27], (Key::GUI_Right, Press)),
            (vec![0xE0, 0x28], (Key::Multimedia_WWW_Stop, Press)),
            (vec![0xE0, 0x2B], (Key::Multimedia_Calculator, Press)),
            (vec![0xE0, 0x2F], (Key::Apps, Press)),
            (vec![0xE0, 0x30], (Key::Multimedia_WWW_Forward, Press)),
            (vec![0xE0, 0x32], (Key::Multimedia_VolumeUp, Press)),
            (vec![0xE0, 0x34], (Key::Multimedia_PlayPause, Press)),
            (vec![0xE0, 0x37], (Key::ACPI_Power, Press)),
            (vec![0xE0, 0x38], (Key::Multimedia_WWW_Back, Press)),
            (vec![0xE0, 0x3A], (Key::Multimedia_WWW_Home, Press)),
            (vec![0xE0, 0x3B], (Key::Multimedia_Stop, Press)),
            (vec![0xE0, 0x3F], (Key::ACPI_Sleep, Press)),
            (vec![0xE0, 0x40], (Key::Multimedia_My_Computer, Press)),
            (vec![0xE0, 0x48], (Key::Multimedia_Email, Press)),
            (vec![0xE0, 0x4A], (Key::Keypad_Divide, Press)),
            (vec![0xE0, 0x4D], (Key::Multimedia_NextTrack, Press)),
            (vec![0xE0, 0x50], (Key::Multimedia_MediaSelect, Press)),
            (vec![0xE0, 0x5A], (Key::Keypad_Enter, Press)),
            (vec![0xE0, 0x5E], (Key::ACPI_Wake, Press)),
            (vec![0xE0, 0x69], (Key::End, Press)),
            (vec![0xE0, 0x6B], (Key::CursorLeft, Press)),
            (vec![0xE0, 0x6C], (Key::Home, Press)),
            (vec![0xE0, 0x70], (Key::Insert, Press)),
            (vec![0xE0, 0x71], (Key::Delete, Press)),
            (vec![0xE0, 0x72], (Key::CursorDown, Press)),
            (vec![0xE0, 0x74], (Key::CursorRight, Press)),
            (vec![0xE0, 0x75], (Key::CursorUp, Press)),
            (vec![0xE0, 0x7A], (Key::PageDown, Press)),
            (vec![0xE0, 0x7D], (Key::PageUp, Press)),
            (vec![0xF0, 0x01], (Key::F9, Release)),
            (vec![0xF0, 0x03], (Key::F5, Release)),
            (vec![0xF0, 0x04], (Key::F3, Release)),
            (vec![0xF0, 0x05], (Key::F1, Release)),
            (vec![0xF0, 0x06], (Key::F2, Release)),
            (vec![0xF0, 0x07], (Key::F12, Release)),
            (vec![0xF0, 0x09], (Key::F10, Release)),
            (vec![0xF0, 0x0A], (Key::F8, Release)),
            (vec![0xF0, 0x0B], (Key::F6, Release)),
            (vec![0xF0, 0x0C], (Key::F4, Release)),
            (vec![0xF0, 0x0D], (Key::Tab, Release)),
            (vec![0xF0, 0x0E], (Key::Backtick, Release)),
            (vec![0xF0, 0x11], (Key::LeftAlt, Release)),
            (vec![0xF0, 0x12], (Key::LeftShift, Release)),
            (vec![0xF0, 0x14], (Key::LeftControl, Release)),
            (vec![0xF0, 0x15], (Key::Q, Release)),
            (vec![0xF0, 0x16], (Key::K1, Release)),
            (vec![0xF0, 0x1A], (Key::Z, Release)),
            (vec![0xF0, 0x1B], (Key::S, Release)),
            (vec![0xF0, 0x1C], (Key::A, Release)),
            (vec![0xF0, 0x1D], (Key::W, Release)),
            (vec![0xF0, 0x1E], (Key::K2, Release)),
            (vec![0xF0, 0x21], (Key::C, Release)),
            (vec![0xF0, 0x22], (Key::X, Release)),
            (vec![0xF0, 0x23], (Key::D, Release)),
            (vec![0xF0, 0x24], (Key::E, Release)),
            (vec![0xF0, 0x25], (Key::K4, Release)),
            (vec![0xF0, 0x26], (Key::K3, Release)),
            (vec![0xF0, 0x29], (Key::Space, Release)),
            (vec![0xF0, 0x2A], (Key::V, Release)),
            (vec![0xF0, 0x2B], (Key::F, Release)),
            (vec![0xF0, 0x2C], (Key::T, Release)),
            (vec![0xF0, 0x2D], (Key::R, Release)),
            (vec![0xF0, 0x2E], (Key::K5, Release)),
            (vec![0xF0, 0x31], (Key::N, Release)),
            (vec![0xF0, 0x32], (Key::B, Release)),
            (vec![0xF0, 0x33], (Key::H, Release)),
            (vec![0xF0, 0x34], (Key::G, Release)),
            (vec![0xF0, 0x35], (Key::Y, Release)),
            (vec![0xF0, 0x36], (Key::K6, Release)),
            (vec![0xF0, 0x3A], (Key::M, Release)),
            (vec![0xF0, 0x3B], (Key::J, Release)),
            (vec![0xF0, 0x3C], (Key::U, Release)),
            (vec![0xF0, 0x3D], (Key::K7, Release)),
            (vec![0xF0, 0x3E], (Key::K8, Release)),
            (vec![0xF0, 0x41], (Key::Comma, Release)),
            (vec![0xF0, 0x42], (Key::K, Release)),
            (vec![0xF0, 0x43], (Key::I, Release)),
            (vec![0xF0, 0x44], (Key::O, Release)),
            (vec![0xF0, 0x45], (Key::K0, Release)),
            (vec![0xF0, 0x46], (Key::K9, Release)),
            (vec![0xF0, 0x49], (Key::Period, Release)),
            (vec![0xF0, 0x4A], (Key::Slash, Release)),
            (vec![0xF0, 0x4B], (Key::L, Release)),
            (vec![0xF0, 0x4C], (Key::Semicolon, Release)),
            (vec![0xF0, 0x4D], (Key::P, Release)),
            (vec![0xF0, 0x4E], (Key::Minus, Release)),
            (vec![0xF0, 0x52], (Key::Singlequote, Release)),
            (vec![0xF0, 0x54], (Key::LeftBracket, Release)),
            (vec![0xF0, 0x55], (Key::Equals, Release)),
            (vec![0xF0, 0x58], (Key::CapsLock, Release)),
            (vec![0xF0, 0x59], (Key::RightShift, Release)),
            (vec![0xF0, 0x5A], (Key::Enter, Release)),
            (vec![0xF0, 0x5B], (Key::RightBracket, Release)),
            (vec![0xF0, 0x5D], (Key::Backslash, Release)),
            (vec![0xF0, 0x66], (Key::Backspace, Release)),
            (vec![0xF0, 0x69], (Key::Keypad_1, Release)),
            (vec![0xF0, 0x6B], (Key::Keypad_4, Release)),
            (vec![0xF0, 0x6C], (Key::Keypad_7, Release)),
            (vec![0xF0, 0x70], (Key::Keypad_0, Release)),
            (vec![0xF0, 0x71], (Key::Keypad_Period, Release)),
            (vec![0xF0, 0x72], (Key::Keypad_2, Release)),
            (vec![0xF0, 0x73], (Key::Keypad_5, Release)),
            (vec![0xF0, 0x74], (Key::Keypad_6, Release)),
            (vec![0xF0, 0x75], (Key::Keypad_8, Release)),
            (vec![0xF0, 0x76], (Key::Escape, Release)),
            (vec![0xF0, 0x77], (Key::NumberLock, Release)),
            (vec![0xF0, 0x78], (Key::F11, Release)),
            (vec![0xF0, 0x79], (Key::Keypad_Plus, Release)),
            (vec![0xF0, 0x7A], (Key::Keypad_3, Release)),
            (vec![0xF0, 0x7B], (Key::Keypad_Minus, Release)),
            (vec![0xF0, 0x7C], (Key::Keypad_Multiply, Release)),
            (vec![0xF0, 0x7D], (Key::Keypad_9, Release)),
            (vec![0xF0, 0x7E], (Key::ScrollLock, Release)),
            (vec![0xF0, 0x83], (Key::F7, Release)),
            (vec![0xE0, 0x12, 0xE0, 0x7C], (Key::PrintScreen, Press)),
            (vec![0xE0, 0xF0, 0x10], (Key::Multimedia_WWW_Search, Release)),
            (vec![0xE0, 0xF0, 0x11], (Key::RightAlt, Release)),
            (vec![0xE0, 0xF0, 0x14], (Key::RightControl, Release)),
            (vec![0xE0, 0xF0, 0x15], (Key::Multimedia_PreviousTrack, Release)),
            (vec![0xE0, 0xF0, 0x18], (Key::Multimedia_WWW_Favourites, Release)),
            (vec![0xE0, 0xF0, 0x1F], (Key::GUI_Left, Release)),
            (vec![0xE0, 0xF0, 0x20], (Key::Multimedia_WWW_Refresh, Release)),
            (vec![0xE0, 0xF0, 0x21], (Key::Multimedia_VolumeDown, Release)),
            (vec![0xE0, 0xF0, 0x23], (Key::Multimedia_Mute, Release)),
            (vec![0xE0, 0xF0, 0x27], (Key::GUI_Right, Release)),
            (vec![0xE0, 0xF0, 0x28], (Key::Multimedia_WWW_Stop, Release)),
            (vec![0xE0, 0xF0, 0x2B], (Key::Multimedia_Calculator, Release)),
            (vec![0xE0, 0xF0, 0x2F], (Key::Apps, Release)),
            (vec![0xE0, 0xF0, 0x30], (Key::Multimedia_WWW_Forward, Release)),
            (vec![0xE0, 0xF0, 0x32], (Key::Multimedia_VolumeUp, Release)),
            (vec![0xE0, 0xF0, 0x34], (Key::Multimedia_PlayPause, Release)),
            (vec![0xE0, 0xF0, 0x37], (Key::ACPI_Power, Release)),
            (vec![0xE0, 0xF0, 0x38], (Key::Multimedia_WWW_Back, Release)),
            (vec![0xE0, 0xF0, 0x3A], (Key::Multimedia_WWW_Home, Release)),
            (vec![0xE0, 0xF0, 0x3B], (Key::Multimedia_Stop, Release)),
            (vec![0xE0, 0xF0, 0x3F], (Key::ACPI_Sleep, Release)),
            (vec![0xE0, 0xF0, 0x40], (Key::Multimedia_MyComputer, Release)),
            (vec![0xE0, 0xF0, 0x48], (Key::Multimedia_Email, Release)),
            (vec![0xE0, 0xF0, 0x4A], (Key::Keypad_Divide, Release)),
            (vec![0xE0, 0xF0, 0x4D], (Key::Multimedia_NextTrack, Release)),
            (vec![0xE0, 0xF0, 0x50], (Key::Multimedia_MediaSelect, Release)),
            (vec![0xE0, 0xF0, 0x5A], (Key::Keypad_Enter, Release)),
            (vec![0xE0, 0xF0, 0x5E], (Key::ACPI_Wake, Release)),
            (vec![0xE0, 0xF0, 0x69], (Key::End, Release)),
            (vec![0xE0, 0xF0, 0x6B], (Key::CursorLeft, Release)),
            (vec![0xE0, 0xF0, 0x6C], (Key::Home, Release)),
            (vec![0xE0, 0xF0, 0x70], (Key::Insert, Release)),
            (vec![0xE0, 0xF0, 0x71], (Key::Delete, Release)),
            (vec![0xE0, 0xF0, 0x72], (Key::CursorDown, Release)),
            (vec![0xE0, 0xF0, 0x74], (Key::CursorRight, Release)),
            (vec![0xE0, 0xF0, 0x75], (Key::CursorUp, Release)),
            (vec![0xE0, 0xF0, 0x7A], (Key::PageDown, Release)),
            (vec![0xE0, 0xF0, 0x7D], (Key::PageUp, Release)),
            (vec![0xE0, 0xF0, 0x7C, 0xE0, 0xF0, 0x12], (Key::PrintScreen, Release)),
            (vec![0xE1, 0x14, 0x77, 0xE1, 0xF0, 0x14, 0xF0, 0x77], (Key::Pause, Press)),
        ]);
    }

    pub fn get(&self, v: Vec<u8>) -> Option<KeyboardEvent> {
        match self.mapping {
            Some(ref mapping) => {
                mapping.iter()
                .find(|x| x.0==v).map(|x| x.1)
                .map(|x| KeyboardEvent::new(x.0, x.1))
            },
            None => None
        }
    }
}
