#![allow(clippy::unreadable_literal)]
//! Constants memory-related things

use super::prelude::*;

// Autogenerated part
include!("../../build/constants.rs");

pub const HEAP_START: u64 = 0x4000_0000; // At 1 GiB
pub const HEAP_SIZE: u64 = 0x640_0000; // 100 MiB heap
